package org.tindalos.principle.infrastructure.reporters

import org.tindalos.principle.domain.analyzers.submodulesblueprint.SubmodulesBlueprintAnalysisResult

trait SubmodulesBlueprintAnalysisResultReporter extends AnalysisResultReporter[SubmodulesBlueprintAnalysisResult]